### ISSUE TITLE
Wrong commit

### ISSUE THREAD

**Issue by faisal-developersbd** [sudar/AdjustVolume#1]
The project source code is wrongly committed. There is java code here. Please commit correctly.

**Comment by sudar** [comment]
@faisal-developersbd 

> AdjustVolume is an android app that allows you to adjust the volume of your android phone.

This repo is for an Android app and Android app is developed using Java code.

Not sure why you feel that there should not be Java code in an Android app.

**Comment by faisal-developersbd** [comment]
@sudar Issue resolved! Thanks.
